CREATE PROCEDURE PREMPLOYEEINSERT
(
@NAME          VARCHAR(200),
@GENDER        VARCHAR(100),
@SALARY        DECIMAL (10,2),
@DATEOFJOIN    VARCHAR(100)
)
AS
BEGIN
INSERT INTO TBLEMPLOYEE
(
FLDEMPLOYEENAME ,FLDGENDER ,FLDSALARY ,FLDDATEOFJOIN           
)
VALUES
(
@NAME,
@GENDER,
@SALARY,
@DATEOFJOIN  
) 
END