
CREATE TABLE TBLEMPLOYEE 
(
FLDEMPLOYEEID     int  IDENTITY(0,1) ,
FLDEMPLOYEENAME   VARCHAR(200)      NOT NULL,
FLDGENDER            VARCHAR(100) , 
FLDSALARY          DECIMAL (10,2)  ,
FLDDATEOFJOIN  VARCHAR(100),
 );


 
ALTER TABLE TBLEMPLOYEE
ADD CONSTRAINT PK_TBLEMPLOYEE_FLDEMPLOYEEID PRIMARY KEY (FLDEMPLOYEEID);

ALTER TABLE TBLEMPLOYEE
ADD CONSTRAINT UNQ_TBLEMPLOYEE_FLDEMPLOYEEID  UNIQUE(FLDEMPLOYEEID); 