CREATE TABLE [dbo].[TBLMOBILEUSERSIGNUP](
	[FLDUSERID] [uniqueidentifier] NULL,
	[FLDUSERNAME] [varchar](500) NULL,
	[FLDPASSWORD] [varchar](500) NULL,
	[FLDCREATEDDATE] [datetime] NULL,
	[FLDCREATEDBY] [int] NULL,
	[FLDMODIFIEDDATE] [datetime] NULL,
	[FLDMODIFIEDBY] [int] NULL,
	[FLDDTKEY] [uniqueidentifier] NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TBLMOBILEUSERSIGNUP] ADD  CONSTRAINT [DF_TBLMOBILEUSERSIGNUP_FLDUSERID]  DEFAULT (newsequentialid()) FOR [FLDUSERID]
GO

ALTER TABLE [dbo].[TBLMOBILEUSERSIGNUP] ADD  CONSTRAINT [DF_TBLMOBILEUSERSIGNUP_FLDDTKEY]  DEFAULT (newsequentialid()) FOR [FLDDTKEY]
GO

select * from [TBLMOBILEUSERSIGNUP]