CREATE TABLE TBLPLACES 
(
FLDPLACESID     int  IDENTITY(0,1) ,
FLDPLACESNAME   VARCHAR(200)      NOT NULL,
FLDIMAGEURL            VARCHAR(100) NOT NULL , 
 );


 ALTER TABLE TBLPLACES
ADD CONSTRAINT PK_TBLPLACES_FLDPLACESID PRIMARY KEY (FLDPLACESID);
